### ISSUE TITLE
killMS.py is not working--> ImportError: No module named Other

### ISSUE THREAD

**Issue by botteon** [saopicc/killMS#5] opened 2019-05-16 14:01 UTC
Hi,

we have installed lofar-stable branch in Bologna. Apparently there is an issue with killMS.py; it returns

```
Traceback (most recent call last):
  File "/opt/killMS/killMS.py", line 28, in <module>
    from killMS.Other import MyPickle
  File "/opt/killMS/killMS.py", line 28, in <module>
    from killMS.Other import MyPickle
ImportError: No module named Other
```

Note that we have defined

`PYTHONPATH=/opt/killMS/:$PYTHONPATH`

**Comment by mhardcastle** [comment] 2019-05-16 15:07
Duplicate of #3. You'll need to have `/opt` on your PYTHONPATH.

**Closed as completed by mhardcastle** 2019-05-16 15:07 UTC
